[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
authors = [
    {name = "amine", email = "amine10ouchaadid@gmail.com"}
]

[tool.setuptools.packages.find]
include = ["ft_package*"]